import turtle
import random

turtle.shape('turtle')
global r, g, b
r = random.random()
g = random.random()
b = random.random()
turtle.pencolor(r, g, b)
turtle.pensize(4)

turtle.left(60)
turtle.forward(200)
turtle.right(145)
turtle.forward(200)
turtle.right(145)
turtle.forward(200)
turtle.right(135)
turtle.forward(200)
turtle.right(145)
turtle.forward(218)
turtle.penup()
turtle.right(130)
turtle.forward(170)
r = random.random()
g = random.random()
b = random.random()
turtle.pencolor(r, g, b)
turtle.pendown()
turtle.right(155)
turtle.forward(200)
turtle.left(145)
turtle.forward(200)
turtle.left(145)
turtle.forward(200)
turtle.left(135)
turtle.forward(200)
turtle.left(145)
turtle.forward(218)
turtle.left(90)
turtle.penup()
turtle.right(10)
turtle.forward(10)
r = random.random()
g = random.random()
b = random.random()
turtle.pencolor(r, g, b)
turtle.pendown()
turtle.circle(110)


turtle.done()
